paginate: 10
paginate_path: "page:num"

highlighter: pygments
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      title: samet's scratchpad
description: Makarnayı seviyorum; ama beşamel soslu, kıymalı ve de fırında oldurulacaksa.

author:
  name: Samet TEMIZER
  email: info@stemizer.net
  github: nestisamet
  twitter: nestisamet
  youtube: stemizer
  stackoverflow: 000/foo
  bio: Think twice.. Code once..
  email_md5: 4fbccb663967e0b20f086ccb428641c7

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:

exclude:
 - README.md
 - _drafts